services:
  app:
    build: .
    container_name: interview-app
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATA_URL=${DATA_URL:-}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
