services:
  app:
    build: .
    container_name: interview-app
    ports:
      - "80:80"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATA_URL=${DATA_URL:-}
      - PROXY_URL=http://127.0.0.1:1081
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
